[project]
org-name= "kanishka"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java11"

[[platform.libraries]]
path = "./src/db/resources/mysql-connector-java-8.0.18.jar"
modules = ["db"]